/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Monitor Agent API
 * REST API for system, hardware, and software monitoring.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiV1AgentFile400,
  InternalApiAgentActionResponse,
  InternalApiHealthResponse,
  InternalApiMetricsResponse
} from './models';

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiV1AgentFileResponse200 = {
  data: Blob
  status: 200
}

export type getApiV1AgentFileResponse400 = {
  data: GetApiV1AgentFile400
  status: 400
}

export type getApiV1AgentFileResponseSuccess = (getApiV1AgentFileResponse200) & {
  headers: Headers;
};
export type getApiV1AgentFileResponseError = (getApiV1AgentFileResponse400) & {
  headers: Headers;
};

export type getApiV1AgentFileResponse = (getApiV1AgentFileResponseSuccess | getApiV1AgentFileResponseError)

export const getGetApiV1AgentFileUrl = () => {




  return `/api/v1/agent/file`
}

/**
 * Triggers report file generation by the agent.
 * @summary Generate output file
 */
export const getApiV1AgentFile = async ( options?: RequestInit): Promise<getApiV1AgentFileResponse> => {

  const res = await fetch(getGetApiV1AgentFileUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.blob();
  const data: getApiV1AgentFileResponse['data'] = body as getApiV1AgentFileResponse['data']
  return { data, status: res.status, headers: res.headers } as getApiV1AgentFileResponse
}





export const getGetApiV1AgentFileQueryKey = () => {
    return [
    `/api/v1/agent/file`
    ] as const;
    }


export const getGetApiV1AgentFileQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AgentFile>>, TError = GetApiV1AgentFile400>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AgentFile>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AgentFileQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AgentFile>>> = ({ signal }) => getApiV1AgentFile({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AgentFile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AgentFileQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AgentFile>>>
export type GetApiV1AgentFileQueryError = GetApiV1AgentFile400


export function useGetApiV1AgentFile<TData = Awaited<ReturnType<typeof getApiV1AgentFile>>, TError = GetApiV1AgentFile400>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AgentFile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AgentFile>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AgentFile>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AgentFile<TData = Awaited<ReturnType<typeof getApiV1AgentFile>>, TError = GetApiV1AgentFile400>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AgentFile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AgentFile>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AgentFile>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AgentFile<TData = Awaited<ReturnType<typeof getApiV1AgentFile>>, TError = GetApiV1AgentFile400>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AgentFile>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Generate output file
 */

export function useGetApiV1AgentFile<TData = Awaited<ReturnType<typeof getApiV1AgentFile>>, TError = GetApiV1AgentFile400>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AgentFile>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AgentFileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getApiV1AgentMetricsResponse200 = {
  data: InternalApiMetricsResponse
  status: 200
}

export type getApiV1AgentMetricsResponse500 = {
  data: InternalApiAgentActionResponse
  status: 500
}

export type getApiV1AgentMetricsResponseSuccess = (getApiV1AgentMetricsResponse200) & {
  headers: Headers;
};
export type getApiV1AgentMetricsResponseError = (getApiV1AgentMetricsResponse500) & {
  headers: Headers;
};

export type getApiV1AgentMetricsResponse = (getApiV1AgentMetricsResponseSuccess | getApiV1AgentMetricsResponseError)

export const getGetApiV1AgentMetricsUrl = () => {




  return `/api/v1/agent/metrics`
}

/**
 * Returns an array of all collected metrics from cache.
 * @summary Get collected metrics
 */
export const getApiV1AgentMetrics = async ( options?: RequestInit): Promise<getApiV1AgentMetricsResponse> => {

  const res = await fetch(getGetApiV1AgentMetricsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiV1AgentMetricsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiV1AgentMetricsResponse
}





export const getGetApiV1AgentMetricsQueryKey = () => {
    return [
    `/api/v1/agent/metrics`
    ] as const;
    }


export const getGetApiV1AgentMetricsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AgentMetrics>>, TError = InternalApiAgentActionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AgentMetrics>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AgentMetricsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AgentMetrics>>> = ({ signal }) => getApiV1AgentMetrics({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AgentMetrics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AgentMetricsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AgentMetrics>>>
export type GetApiV1AgentMetricsQueryError = InternalApiAgentActionResponse


export function useGetApiV1AgentMetrics<TData = Awaited<ReturnType<typeof getApiV1AgentMetrics>>, TError = InternalApiAgentActionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AgentMetrics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AgentMetrics>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AgentMetrics>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AgentMetrics<TData = Awaited<ReturnType<typeof getApiV1AgentMetrics>>, TError = InternalApiAgentActionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AgentMetrics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AgentMetrics>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AgentMetrics>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AgentMetrics<TData = Awaited<ReturnType<typeof getApiV1AgentMetrics>>, TError = InternalApiAgentActionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AgentMetrics>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get collected metrics
 */

export function useGetApiV1AgentMetrics<TData = Awaited<ReturnType<typeof getApiV1AgentMetrics>>, TError = InternalApiAgentActionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AgentMetrics>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AgentMetricsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type postApiV1AgentStartResponse200 = {
  data: InternalApiAgentActionResponse
  status: 200
}

export type postApiV1AgentStartResponse400 = {
  data: InternalApiAgentActionResponse
  status: 400
}

export type postApiV1AgentStartResponseSuccess = (postApiV1AgentStartResponse200) & {
  headers: Headers;
};
export type postApiV1AgentStartResponseError = (postApiV1AgentStartResponse400) & {
  headers: Headers;
};

export type postApiV1AgentStartResponse = (postApiV1AgentStartResponseSuccess | postApiV1AgentStartResponseError)

export const getPostApiV1AgentStartUrl = () => {




  return `/api/v1/agent/start`
}

/**
 * Starts background metrics collection loop.
 * @summary Start agent
 */
export const postApiV1AgentStart = async ( options?: RequestInit): Promise<postApiV1AgentStartResponse> => {

  const res = await fetch(getPostApiV1AgentStartUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiV1AgentStartResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiV1AgentStartResponse
}





export const getPostApiV1AgentStartMutationOptions = <TError = InternalApiAgentActionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AgentStart>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AgentStart>>, TError,void, TContext> => {

const mutationKey = ['postApiV1AgentStart'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AgentStart>>, void> = () => {


          return  postApiV1AgentStart(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AgentStartMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AgentStart>>>

    export type PostApiV1AgentStartMutationError = InternalApiAgentActionResponse

    /**
 * @summary Start agent
 */
export const usePostApiV1AgentStart = <TError = InternalApiAgentActionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AgentStart>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AgentStart>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiV1AgentStartMutationOptions(options), queryClient);
    }

export type postApiV1AgentStopResponse200 = {
  data: InternalApiAgentActionResponse
  status: 200
}

export type postApiV1AgentStopResponse400 = {
  data: InternalApiAgentActionResponse
  status: 400
}

export type postApiV1AgentStopResponseSuccess = (postApiV1AgentStopResponse200) & {
  headers: Headers;
};
export type postApiV1AgentStopResponseError = (postApiV1AgentStopResponse400) & {
  headers: Headers;
};

export type postApiV1AgentStopResponse = (postApiV1AgentStopResponseSuccess | postApiV1AgentStopResponseError)

export const getPostApiV1AgentStopUrl = () => {




  return `/api/v1/agent/stop`
}

/**
 * Stops the active agent loop.
 * @summary Stop agent
 */
export const postApiV1AgentStop = async ( options?: RequestInit): Promise<postApiV1AgentStopResponse> => {

  const res = await fetch(getPostApiV1AgentStopUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiV1AgentStopResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiV1AgentStopResponse
}





export const getPostApiV1AgentStopMutationOptions = <TError = InternalApiAgentActionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AgentStop>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AgentStop>>, TError,void, TContext> => {

const mutationKey = ['postApiV1AgentStop'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AgentStop>>, void> = () => {


          return  postApiV1AgentStop(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AgentStopMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AgentStop>>>

    export type PostApiV1AgentStopMutationError = InternalApiAgentActionResponse

    /**
 * @summary Stop agent
 */
export const usePostApiV1AgentStop = <TError = InternalApiAgentActionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AgentStop>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AgentStop>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiV1AgentStopMutationOptions(options), queryClient);
    }

export type getApiV1HealthResponse200 = {
  data: InternalApiHealthResponse
  status: 200
}

export type getApiV1HealthResponseSuccess = (getApiV1HealthResponse200) & {
  headers: Headers;
};
;

export type getApiV1HealthResponse = (getApiV1HealthResponseSuccess)

export const getGetApiV1HealthUrl = () => {




  return `/api/v1/health`
}

/**
 * Returns the current agent running state (running/stopped) along with HATEOAS navigation links.
 * @summary Check agent status
 */
export const getApiV1Health = async ( options?: RequestInit): Promise<getApiV1HealthResponse> => {

  const res = await fetch(getGetApiV1HealthUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiV1HealthResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiV1HealthResponse
}





export const getGetApiV1HealthQueryKey = () => {
    return [
    `/api/v1/health`
    ] as const;
    }


export const getGetApiV1HealthQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Health>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1HealthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Health>>> = ({ signal }) => getApiV1Health({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1HealthQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Health>>>
export type GetApiV1HealthQueryError = unknown


export function useGetApiV1Health<TData = Awaited<ReturnType<typeof getApiV1Health>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Health>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Health>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Health<TData = Awaited<ReturnType<typeof getApiV1Health>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Health>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Health>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Health<TData = Awaited<ReturnType<typeof getApiV1Health>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Check agent status
 */

export function useGetApiV1Health<TData = Awaited<ReturnType<typeof getApiV1Health>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1HealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
