/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Monitor Agent API
 * REST API for system, hardware, and software monitoring.
 * OpenAPI spec version: 1.0
 */

export * from './getApiV1AgentFile400';
export * from './internalApiAgentActionResponse';
export * from './internalApiHealthResponse';
export * from './internalApiLink';
export * from './internalApiMetricsResponse';
export * from './monitoringSystemInternalHardwareBatteryBatteryInformation';
export * from './monitoringSystemInternalHardwareBiosBiosInformation';
export * from './monitoringSystemInternalHardwareCompleteHardwareInformation';
export * from './monitoringSystemInternalHardwareCpuCPUInformation';
export * from './monitoringSystemInternalHardwareGpuGPUInformation';
export * from './monitoringSystemInternalHardwareIoDiskIO';
export * from './monitoringSystemInternalHardwareIoIOStatistics';
export * from './monitoringSystemInternalHardwareIoIOStatisticsDisk';
export * from './monitoringSystemInternalHardwareIoIOStatisticsNetwork';
export * from './monitoringSystemInternalHardwareIoNetworkIO';
export * from './monitoringSystemInternalHardwareMemoryMemoryInformation';
export * from './monitoringSystemInternalHardwareMotherboardMotherboardInformation';
export * from './monitoringSystemInternalHardwareNetworkNetworkInformation';
export * from './monitoringSystemInternalHardwarePeripheralsDisplayInformation';
export * from './monitoringSystemInternalHardwarePeripheralsPeripheralsInformation';
export * from './monitoringSystemInternalHardwarePeripheralsUSBDeviceInformation';
export * from './monitoringSystemInternalHardwareSensorsSensorInformation';
export * from './monitoringSystemInternalHardwareStorageStorageInformation';
export * from './monitoringSystemInternalMetricsMetrics';
export * from './monitoringSystemInternalSoftwareApplicationsApplicationInformation';
export * from './monitoringSystemInternalSoftwareCompleteSoftwareInformation';
export * from './monitoringSystemInternalSoftwareDriversDriverInformation';
export * from './monitoringSystemInternalSoftwareNetworkNetworkAdapterInformation';
export * from './monitoringSystemInternalSoftwareOperatingSystemOperatingSystemInformation';
export * from './monitoringSystemInternalSoftwareServicesServiceInformation';
export * from './monitoringSystemInternalSoftwareStartupStartupCommandInformation';
export * from './monitoringSystemInternalSoftwareTasksScheduledTaskInformation';
export * from './monitoringSystemInternalSoftwareUpdatesSystemUpdateInformation';
export * from './monitoringSystemInternalSystemCompleteSystemInformation';
export * from './monitoringSystemInternalSystemLoadLoadInformation';
export * from './monitoringSystemInternalSystemOsProcessInformation';
export * from './monitoringSystemInternalSystemOsSystemInformation';
export * from './monitoringSystemInternalSystemUsersUserInformation';
