/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Monitor Agent API
 * REST API for system, hardware, and software monitoring.
 * OpenAPI spec version: 1.0
 */
import type { InternalApiLink } from './internalApiLink';
import type { MonitoringSystemInternalMetricsMetrics } from './monitoringSystemInternalMetricsMetrics';

export interface InternalApiMetricsResponse {
  _links?: InternalApiLink[];
  data?: MonitoringSystemInternalMetricsMetrics[];
  message?: string;
  timestamp?: string;
}
