/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Monitor Agent API
 * REST API for system, hardware, and software monitoring.
 * OpenAPI spec version: 1.0
 */
import type { MonitoringSystemInternalHardwarePeripheralsDisplayInformation } from './monitoringSystemInternalHardwarePeripheralsDisplayInformation';
import type { MonitoringSystemInternalHardwarePeripheralsUSBDeviceInformation } from './monitoringSystemInternalHardwarePeripheralsUSBDeviceInformation';

export interface MonitoringSystemInternalHardwarePeripheralsPeripheralsInformation {
  Displays?: MonitoringSystemInternalHardwarePeripheralsDisplayInformation[];
  USB?: MonitoringSystemInternalHardwarePeripheralsUSBDeviceInformation[];
}
