/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Monitor Agent API
 * REST API for system, hardware, and software monitoring.
 * OpenAPI spec version: 1.0
 */
import type { MonitoringSystemInternalSystemOsProcessInformation } from './monitoringSystemInternalSystemOsProcessInformation';

export interface MonitoringSystemInternalSystemOsSystemInformation {
  Architecture?: string;
  Hostname?: string;
  OS?: string;
  TopProcesses?: MonitoringSystemInternalSystemOsProcessInformation[];
  Uptime?: string;
}
