/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Monitor Agent API
 * REST API for system, hardware, and software monitoring.
 * OpenAPI spec version: 1.0
 */
import type { MonitoringSystemInternalHardwareIoIOStatisticsDisk } from './monitoringSystemInternalHardwareIoIOStatisticsDisk';
import type { MonitoringSystemInternalHardwareIoIOStatisticsNetwork } from './monitoringSystemInternalHardwareIoIOStatisticsNetwork';

export interface MonitoringSystemInternalHardwareIoIOStatistics {
  Disk?: MonitoringSystemInternalHardwareIoIOStatisticsDisk;
  Network?: MonitoringSystemInternalHardwareIoIOStatisticsNetwork;
}
