/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Monitor Agent API
 * REST API for system, hardware, and software monitoring.
 * OpenAPI spec version: 1.0
 */
import type { MonitoringSystemInternalHardwareCompleteHardwareInformation } from './monitoringSystemInternalHardwareCompleteHardwareInformation';
import type { MonitoringSystemInternalSoftwareCompleteSoftwareInformation } from './monitoringSystemInternalSoftwareCompleteSoftwareInformation';
import type { MonitoringSystemInternalSystemCompleteSystemInformation } from './monitoringSystemInternalSystemCompleteSystemInformation';

export interface MonitoringSystemInternalMetricsMetrics {
  hardware?: MonitoringSystemInternalHardwareCompleteHardwareInformation;
  software?: MonitoringSystemInternalSoftwareCompleteSoftwareInformation;
  system?: MonitoringSystemInternalSystemCompleteSystemInformation;
  timestamp?: string;
  trace_id?: string;
}
