/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Monitor Agent API
 * REST API for system, hardware, and software monitoring.
 * OpenAPI spec version: 1.0
 */

export interface MonitoringSystemInternalSystemOsProcessInformation {
  CPUPercent?: number;
  MemoryMB?: number;
  Name?: string;
  PID?: number;
}
