/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Monitor Agent API
 * REST API for system, hardware, and software monitoring.
 * OpenAPI spec version: 1.0
 */

export interface MonitoringSystemInternalSoftwareOperatingSystemOperatingSystemInformation {
  BuildNumber?: string;
  Caption?: string;
  InstallDate?: string;
  LastBootUpTime?: string;
  Manufacturer?: string;
  OSArchitecture?: string;
  Version?: string;
}
