/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Monitor Agent API
 * REST API for system, hardware, and software monitoring.
 * OpenAPI spec version: 1.0
 */
import type { MonitoringSystemInternalSoftwareApplicationsApplicationInformation } from './monitoringSystemInternalSoftwareApplicationsApplicationInformation';
import type { MonitoringSystemInternalSoftwareDriversDriverInformation } from './monitoringSystemInternalSoftwareDriversDriverInformation';
import type { MonitoringSystemInternalSoftwareNetworkNetworkAdapterInformation } from './monitoringSystemInternalSoftwareNetworkNetworkAdapterInformation';
import type { MonitoringSystemInternalSoftwareOperatingSystemOperatingSystemInformation } from './monitoringSystemInternalSoftwareOperatingSystemOperatingSystemInformation';
import type { MonitoringSystemInternalSoftwareServicesServiceInformation } from './monitoringSystemInternalSoftwareServicesServiceInformation';
import type { MonitoringSystemInternalSoftwareStartupStartupCommandInformation } from './monitoringSystemInternalSoftwareStartupStartupCommandInformation';
import type { MonitoringSystemInternalSoftwareTasksScheduledTaskInformation } from './monitoringSystemInternalSoftwareTasksScheduledTaskInformation';
import type { MonitoringSystemInternalSoftwareUpdatesSystemUpdateInformation } from './monitoringSystemInternalSoftwareUpdatesSystemUpdateInformation';

export interface MonitoringSystemInternalSoftwareCompleteSoftwareInformation {
  installed_applications?: MonitoringSystemInternalSoftwareApplicationsApplicationInformation[];
  network_adapters?: MonitoringSystemInternalSoftwareNetworkNetworkAdapterInformation[];
  operating_system?: MonitoringSystemInternalSoftwareOperatingSystemOperatingSystemInformation;
  scheduled_tasks?: MonitoringSystemInternalSoftwareTasksScheduledTaskInformation[];
  startup_commands?: MonitoringSystemInternalSoftwareStartupStartupCommandInformation[];
  system_drivers?: MonitoringSystemInternalSoftwareDriversDriverInformation[];
  system_services?: MonitoringSystemInternalSoftwareServicesServiceInformation[];
  system_updates?: MonitoringSystemInternalSoftwareUpdatesSystemUpdateInformation[];
}
