/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Monitor Agent API
 * REST API for system, hardware, and software monitoring.
 * OpenAPI spec version: 1.0
 */
import type { MonitoringSystemInternalSystemLoadLoadInformation } from './monitoringSystemInternalSystemLoadLoadInformation';
import type { MonitoringSystemInternalSystemOsSystemInformation } from './monitoringSystemInternalSystemOsSystemInformation';
import type { MonitoringSystemInternalSystemUsersUserInformation } from './monitoringSystemInternalSystemUsersUserInformation';

export interface MonitoringSystemInternalSystemCompleteSystemInformation {
  load?: MonitoringSystemInternalSystemLoadLoadInformation;
  system?: MonitoringSystemInternalSystemOsSystemInformation;
  users?: MonitoringSystemInternalSystemUsersUserInformation[];
}
