/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Monitor Agent API
 * REST API for system, hardware, and software monitoring.
 * OpenAPI spec version: 1.0
 */
import type { MonitoringSystemInternalHardwareBatteryBatteryInformation } from './monitoringSystemInternalHardwareBatteryBatteryInformation';
import type { MonitoringSystemInternalHardwareBiosBiosInformation } from './monitoringSystemInternalHardwareBiosBiosInformation';
import type { MonitoringSystemInternalHardwareCpuCPUInformation } from './monitoringSystemInternalHardwareCpuCPUInformation';
import type { MonitoringSystemInternalHardwareGpuGPUInformation } from './monitoringSystemInternalHardwareGpuGPUInformation';
import type { MonitoringSystemInternalHardwareIoIOStatistics } from './monitoringSystemInternalHardwareIoIOStatistics';
import type { MonitoringSystemInternalHardwareMemoryMemoryInformation } from './monitoringSystemInternalHardwareMemoryMemoryInformation';
import type { MonitoringSystemInternalHardwareMotherboardMotherboardInformation } from './monitoringSystemInternalHardwareMotherboardMotherboardInformation';
import type { MonitoringSystemInternalHardwareNetworkNetworkInformation } from './monitoringSystemInternalHardwareNetworkNetworkInformation';
import type { MonitoringSystemInternalHardwarePeripheralsPeripheralsInformation } from './monitoringSystemInternalHardwarePeripheralsPeripheralsInformation';
import type { MonitoringSystemInternalHardwareSensorsSensorInformation } from './monitoringSystemInternalHardwareSensorsSensorInformation';
import type { MonitoringSystemInternalHardwareStorageStorageInformation } from './monitoringSystemInternalHardwareStorageStorageInformation';

export interface MonitoringSystemInternalHardwareCompleteHardwareInformation {
  battery?: MonitoringSystemInternalHardwareBatteryBatteryInformation[];
  bios?: MonitoringSystemInternalHardwareBiosBiosInformation;
  cpu?: MonitoringSystemInternalHardwareCpuCPUInformation;
  gpu?: MonitoringSystemInternalHardwareGpuGPUInformation[];
  io?: MonitoringSystemInternalHardwareIoIOStatistics;
  memory?: MonitoringSystemInternalHardwareMemoryMemoryInformation;
  motherboard?: MonitoringSystemInternalHardwareMotherboardMotherboardInformation;
  network?: MonitoringSystemInternalHardwareNetworkNetworkInformation[];
  peripherals?: MonitoringSystemInternalHardwarePeripheralsPeripheralsInformation;
  sensors?: MonitoringSystemInternalHardwareSensorsSensorInformation[];
  storage?: MonitoringSystemInternalHardwareStorageStorageInformation[];
}
